server:
  port: 9530

spring:
  application:
    name: trace-zipkin

eureka:
  instance:
    hostname: localhost
    server:
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka/



