spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shileishmily/config-server.git
          username: shileishmily
          password: shileishmily1228
          search-paths: /**

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
